name: custom_fonts_post
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Gilroy-Black.ttf
          weight: 900
    - family: Gilroy_fixed
      fonts:
        - asset: assets/converted_fonts/Gilroy-Thin.ttf
          weight: 100
        - asset: assets/converted_fonts/Gilroy-UltraLight.ttf
          weight: 200
        - asset: assets/converted_fonts/Gilroy-Light.ttf
          weight: 300
        - asset: assets/converted_fonts/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/converted_fonts/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/converted_fonts/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/converted_fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/converted_fonts/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/converted_fonts/Gilroy-Black.ttf
          weight: 900

  